# Generated by Django 3.2.4 on 2021-11-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testquiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='number_question',
        ),
    ]
