# Generated by Django 3.2.4 on 2021-11-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testquiz', '0002_remove_answers_number_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number_question',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='attempts_quiz',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_point',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='remaining_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
