# Generated by Django 3.2.4 on 2021-11-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testquiz', '0003_auto_20211116_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
